# Generated by Django 3.0.8 on 2020-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pid_protocol2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='protocol2',
            field=models.ManyToManyField(to='accounts.protocol2'),
        ),
    ]
