# Generated by Django 3.0.8 on 2020-07-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_presentation_protocol2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol2',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='protocol2',
            name='title',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='protocol2',
        ),
        migrations.DeleteModel(
            name='pid',
        ),
        migrations.DeleteModel(
            name='protocol2',
        ),
        migrations.DeleteModel(
            name='title',
        ),
    ]
