# Generated by Django 3.0.8 on 2020-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200714_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='name',
        ),
        migrations.AddField(
            model_name='protocol',
            name='pid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
