# Generated by Django 3.0.8 on 2020-07-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200728_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='title',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Final', 'Final')], default='Unspecified', max_length=10, null=True),
        ),
    ]
